### ISSUE TITLE
LogIn

### ISSUE THREAD

**Issue by RandyWS** [graceshopper-pikachu-pack/graceshopper-project#16]
Front End LogIn
- [x] Component to display log in form 
- [x] Store to manage axios request to login

Successful:
- [x] sets new user on state
- [x] pushes to user page

Unsuccessful:
- [x] error handling to show the user what information is incorrect (ex, password incorrect)

Back End Login 
- [x] api route to add JWT if username and password correct
- [x] authentication middleware

**Comment by Adorism** [comment]
tested behavior with correct and incorrect password.
